language: cpp
compiler: gcc
sudo: true
dist: xenial

before_install:
  - sudo apt-add-repository ppa:sonkun/sfml-development --yes
  - sudo apt-get update -qq

install: 
  - sudo apt-get install libsfml-dev

# Xenial
services:
  - xvfb

# Trusty
# Start virtual X server
# before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script: 
 - ./build.sh
 - ./travis_qmake_gcc_cpp98_sfml