language: cpp
compiler: gcc
install:
  - sudo apt-get install libsfm* -y
  # sfml-window
  - sudo apt-get install libx11-dev
  - sudo apt-get install libxcb1-dev
  - sudo apt-get install libx11-xcb-dev
  - sudo apt-get install libxcb-randr0-dev
  - sudo apt-get install libxcb-image0-dev
  - sudo apt-get install libgl1-mesa-dev
  - sudo apt-get install libudev-dev
  # sfml-graphics
  - sudo apt-get install libfreetype6-dev
  - sudo apt-get install libjpeg-dev
  # sfml-audio
  - sudo apt-get install libopenal-dev
  - sudo apt-get install libflac-dev
  - sudo apt-get install libvorbis-dev

script: ./build.sh
